import type { ScenarioDefinition } from "./types";

// Historically accurate scenario daily drawdown paths for Indian markets
// Paths are cumulative return from start (0 = start, negative = drawdown)
// Sampled weekly for data efficiency (~20-30 points per scenario)
// Sources: NIFTY 50, NIFTY Bank, NIFTYBEES, Gold BeES historical data (public record)
// IN scenarios use India-specific crisis windows which closely paralleled US events

export const IN_SCENARIOS: ScenarioDefinition[] = [
  {
    id: "gfc-2008",
    name: "GFC 2008 (India)",
    region: "IN",
    period: { start: "2008-01-01", end: "2009-03-31" },
    description: "Global contagion hit India hard. NIFTY 50 fell ~65% from Jan 2008 peak. FII outflows, INR depreciation, liquidity crisis. Banking stocks hit worst.",
    color: "red",
    factors: {
      equity: -0.55,
      rates: 0.08,
      gold: 0.22,
      usd: -0.22,
      oil: -0.60,
      credit: -0.30,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.55,
        maxDrawdown: -0.65,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.05 },
          { day: 10, drawdown: -0.12 },
          { day: 15, drawdown: -0.20 },
          { day: 20, drawdown: -0.28 },
          { day: 25, drawdown: -0.35 },
          { day: 30, drawdown: -0.42 },
          { day: 35, drawdown: -0.48 },
          { day: 40, drawdown: -0.55 },
          { day: 45, drawdown: -0.60 },
          { day: 50, drawdown: -0.65 },
          { day: 55, drawdown: -0.61 },
          { day: 60, drawdown: -0.63 },
          { day: 65, drawdown: -0.59 },
          { day: 70, drawdown: -0.61 },
          { day: 75, drawdown: -0.58 },
          { day: 80, drawdown: -0.56 },
          { day: 85, drawdown: -0.58 },
          { day: 90, drawdown: -0.55 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.62,
        maxDrawdown: -0.72,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.06 },
          { day: 10, drawdown: -0.14 },
          { day: 15, drawdown: -0.23 },
          { day: 20, drawdown: -0.32 },
          { day: 25, drawdown: -0.40 },
          { day: 30, drawdown: -0.48 },
          { day: 35, drawdown: -0.54 },
          { day: 40, drawdown: -0.61 },
          { day: 45, drawdown: -0.67 },
          { day: 50, drawdown: -0.72 },
          { day: 55, drawdown: -0.68 },
          { day: 60, drawdown: -0.70 },
          { day: 65, drawdown: -0.66 },
          { day: 70, drawdown: -0.68 },
          { day: 75, drawdown: -0.65 },
          { day: 80, drawdown: -0.63 },
          { day: 85, drawdown: -0.65 },
          { day: 90, drawdown: -0.62 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.22,
        maxDrawdown: -0.08,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.02 },
          { day: 10, drawdown: -0.05 },
          { day: 15, drawdown: -0.08 },
          { day: 20, drawdown: -0.04 },
          { day: 25, drawdown: 0.00 },
          { day: 30, drawdown: 0.03 },
          { day: 35, drawdown: 0.06 },
          { day: 40, drawdown: 0.09 },
          { day: 45, drawdown: 0.12 },
          { day: 50, drawdown: 0.14 },
          { day: 55, drawdown: 0.16 },
          { day: 60, drawdown: 0.15 },
          { day: 65, drawdown: 0.17 },
          { day: 70, drawdown: 0.18 },
          { day: 75, drawdown: 0.20 },
          { day: 80, drawdown: 0.19 },
          { day: 85, drawdown: 0.21 },
          { day: 90, drawdown: 0.22 },
        ],
      },
    ],
  },

  {
    id: "covid-2020",
    name: "COVID Crash 2020 (India)",
    region: "IN",
    period: { start: "2020-02-01", end: "2020-04-30" },
    description: "NIFTY 50 crashed 38% in 40 days. India added lockdowns on top of global panic. Small caps hit 45%+. Gold in INR held strong as a safe haven.",
    color: "rose",
    factors: {
      equity: -0.24,
      rates: 0.10,
      gold: 0.12,
      usd: -0.05,
      oil: -0.65,
      credit: -0.18,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.24,
        maxDrawdown: -0.38,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: -0.03 },
          { day: 6, drawdown: -0.08 },
          { day: 9, drawdown: -0.15 },
          { day: 12, drawdown: -0.22 },
          { day: 15, drawdown: -0.28 },
          { day: 18, drawdown: -0.33 },
          { day: 21, drawdown: -0.38 },
          { day: 24, drawdown: -0.34 },
          { day: 27, drawdown: -0.29 },
          { day: 30, drawdown: -0.31 },
          { day: 33, drawdown: -0.27 },
          { day: 36, drawdown: -0.25 },
          { day: 39, drawdown: -0.24 },
          { day: 42, drawdown: -0.23 },
          { day: 45, drawdown: -0.24 },
          { day: 48, drawdown: -0.24 },
          { day: 51, drawdown: -0.24 },
          { day: 54, drawdown: -0.24 },
          { day: 57, drawdown: -0.24 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.35,
        maxDrawdown: -0.48,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: -0.04 },
          { day: 6, drawdown: -0.10 },
          { day: 9, drawdown: -0.18 },
          { day: 12, drawdown: -0.26 },
          { day: 15, drawdown: -0.33 },
          { day: 18, drawdown: -0.40 },
          { day: 21, drawdown: -0.48 },
          { day: 24, drawdown: -0.43 },
          { day: 27, drawdown: -0.37 },
          { day: 30, drawdown: -0.40 },
          { day: 33, drawdown: -0.36 },
          { day: 36, drawdown: -0.33 },
          { day: 39, drawdown: -0.32 },
          { day: 42, drawdown: -0.34 },
          { day: 45, drawdown: -0.35 },
          { day: 48, drawdown: -0.35 },
          { day: 51, drawdown: -0.35 },
          { day: 54, drawdown: -0.35 },
          { day: 57, drawdown: -0.35 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.12,
        maxDrawdown: -0.05,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: 0.02 },
          { day: 6, drawdown: 0.05 },
          { day: 9, drawdown: 0.07 },
          { day: 12, drawdown: 0.04 },
          { day: 15, drawdown: -0.01 },
          { day: 18, drawdown: -0.04 },
          { day: 21, drawdown: -0.05 },
          { day: 24, drawdown: -0.02 },
          { day: 27, drawdown: 0.01 },
          { day: 30, drawdown: 0.03 },
          { day: 33, drawdown: 0.05 },
          { day: 36, drawdown: 0.07 },
          { day: 39, drawdown: 0.09 },
          { day: 42, drawdown: 0.10 },
          { day: 45, drawdown: 0.11 },
          { day: 48, drawdown: 0.12 },
          { day: 51, drawdown: 0.12 },
          { day: 54, drawdown: 0.12 },
          { day: 57, drawdown: 0.12 },
        ],
      },
    ],
  },

  {
    id: "rate-shock-2022",
    name: "Rate Shock 2022 (India)",
    region: "IN",
    period: { start: "2022-01-01", end: "2022-12-31" },
    description: "RBI hiked rates 190bps. NIFTY 50 fell ~17%. Midcap and small cap fell harder. Gold in INR was nearly flat. Banks outperformed broader market.",
    color: "amber",
    factors: {
      equity: -0.17,
      rates: -0.08,
      gold: 0.04,
      usd: -0.10,
      oil: 0.20,
      credit: -0.10,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.17,
        maxDrawdown: -0.22,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.05 },
          { day: 26, drawdown: -0.08 },
          { day: 39, drawdown: -0.05 },
          { day: 52, drawdown: -0.07 },
          { day: 65, drawdown: -0.11 },
          { day: 78, drawdown: -0.14 },
          { day: 91, drawdown: -0.12 },
          { day: 104, drawdown: -0.15 },
          { day: 117, drawdown: -0.18 },
          { day: 130, drawdown: -0.17 },
          { day: 143, drawdown: -0.22 },
          { day: 156, drawdown: -0.19 },
          { day: 169, drawdown: -0.17 },
          { day: 182, drawdown: -0.15 },
          { day: 195, drawdown: -0.16 },
          { day: 208, drawdown: -0.18 },
          { day: 221, drawdown: -0.17 },
          { day: 234, drawdown: -0.17 },
          { day: 247, drawdown: -0.17 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.10,
        maxDrawdown: -0.17,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.04 },
          { day: 26, drawdown: -0.06 },
          { day: 39, drawdown: -0.03 },
          { day: 52, drawdown: -0.05 },
          { day: 65, drawdown: -0.08 },
          { day: 78, drawdown: -0.10 },
          { day: 91, drawdown: -0.08 },
          { day: 104, drawdown: -0.11 },
          { day: 117, drawdown: -0.14 },
          { day: 130, drawdown: -0.13 },
          { day: 143, drawdown: -0.17 },
          { day: 156, drawdown: -0.14 },
          { day: 169, drawdown: -0.12 },
          { day: 182, drawdown: -0.10 },
          { day: 195, drawdown: -0.11 },
          { day: 208, drawdown: -0.13 },
          { day: 221, drawdown: -0.11 },
          { day: 234, drawdown: -0.10 },
          { day: 247, drawdown: -0.10 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.04,
        maxDrawdown: -0.07,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: 0.02 },
          { day: 26, drawdown: 0.04 },
          { day: 39, drawdown: 0.06 },
          { day: 52, drawdown: 0.04 },
          { day: 65, drawdown: 0.01 },
          { day: 78, drawdown: -0.02 },
          { day: 91, drawdown: 0.00 },
          { day: 104, drawdown: -0.03 },
          { day: 117, drawdown: -0.05 },
          { day: 130, drawdown: -0.06 },
          { day: 143, drawdown: -0.07 },
          { day: 156, drawdown: -0.05 },
          { day: 169, drawdown: -0.03 },
          { day: 182, drawdown: -0.02 },
          { day: 195, drawdown: -0.01 },
          { day: 208, drawdown: 0.00 },
          { day: 221, drawdown: 0.02 },
          { day: 234, drawdown: 0.03 },
          { day: 247, drawdown: 0.04 },
        ],
      },
    ],
  },
  {
    id: "recession",
    name: "Recession Shock (India)",
    region: "IN",
    period: { start: "2011-08-01", end: "2012-01-31" },
    description: "Growth slows, risk appetite fades and leveraged or cyclical Indian equities de-rate while gold in INR provides better ballast.",
    color: "sky",
    severity: "Severe",
    shockType: "recession",
    narrative: {
      headline: "Domestic growth scares usually hurt cyclicals first while defensive capital looks for gold and quality balance sheets.",
      howItTransmits: "Recession stress in India typically shows up through weaker demand, funding strain and foreign outflow pressure.",
      dominantDrivers: ["Growth downgrade", "FII outflows", "Credit caution"],
      pressurePoints: ["Banks and cyclicals", "Smaller beta-heavy names", "Discretionary demand"],
      resilienceThemes: ["Gold in INR", "Defensive consumption", "High-quality large caps"],
    },
    assetTypeAdjustments: {
      STOCK: { betaMultiplier: 1.08, confidenceDelta: 0.02, rationale: "Single-name equities in India usually feel recession downgrades more sharply than the benchmark." },
      ETF: { betaMultiplier: 1.02, confidenceDelta: 0.04, rationale: "ETF exposure tracks broad Indian stress better than concentrated names." },
      CRYPTO: { betaMultiplier: 1.15, confidenceDelta: -0.08, rationale: "Crypto behaves like high-beta liquidity risk during macro growth scares." },
      COMMODITY: { betaMultiplier: 0.93, confidenceDelta: -0.01, rationale: "Commodity-linked exposures mix inflation hedging with growth sensitivity." },
      MUTUAL_FUND: { betaMultiplier: 0.96, confidenceDelta: -0.05, rationale: "Fund-style inference lowers confidence versus direct market history." },
    },
    factors: {
      equity: -0.14,
      rates: 0.05,
      gold: 0.12,
      usd: -0.04,
      oil: -0.10,
      credit: -0.09,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.14,
        maxDrawdown: -0.18,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: -0.02 },
          { day: 16, drawdown: -0.05 },
          { day: 24, drawdown: -0.08 },
          { day: 32, drawdown: -0.11 },
          { day: 40, drawdown: -0.14 },
          { day: 48, drawdown: -0.17 },
          { day: 56, drawdown: -0.18 },
          { day: 64, drawdown: -0.16 },
          { day: 72, drawdown: -0.15 },
          { day: 80, drawdown: -0.14 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.18,
        maxDrawdown: -0.23,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: -0.03 },
          { day: 16, drawdown: -0.06 },
          { day: 24, drawdown: -0.10 },
          { day: 32, drawdown: -0.14 },
          { day: 40, drawdown: -0.17 },
          { day: 48, drawdown: -0.20 },
          { day: 56, drawdown: -0.23 },
          { day: 64, drawdown: -0.21 },
          { day: 72, drawdown: -0.19 },
          { day: 80, drawdown: -0.18 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.12,
        maxDrawdown: -0.03,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: 0.01 },
          { day: 16, drawdown: 0.04 },
          { day: 24, drawdown: 0.06 },
          { day: 32, drawdown: 0.08 },
          { day: 40, drawdown: 0.05 },
          { day: 48, drawdown: 0.02 },
          { day: 56, drawdown: -0.03 },
          { day: 64, drawdown: 0.01 },
          { day: 72, drawdown: 0.07 },
          { day: 80, drawdown: 0.12 },
        ],
      },
    ],
  },
  {
    id: "interest-rate-shock",
    name: "Interest Rate Shock (India)",
    region: "IN",
    period: { start: "2013-05-01", end: "2013-09-30" },
    description: "Bond yields jump, the rupee weakens and duration-heavy or imported-cost-sensitive businesses get repriced quickly.",
    color: "amber",
    severity: "Severe",
    shockType: "rate-shock",
    narrative: {
      headline: "A faster-than-expected rate repricing hits duration, funding costs and imported inflation all at once.",
      howItTransmits: "Indian rate shocks move through bond losses, rupee weakness and valuation compression in rate-sensitive sectors.",
      dominantDrivers: ["Yield repricing", "Rupee stress", "Funding-cost pressure"],
      pressurePoints: ["Rate-sensitive growth", "NBFCs and duration exposure", "Import-heavy sectors"],
      resilienceThemes: ["Banks with deposit strength", "Gold in INR", "Cash-flow-heavy value"],
    },
    assetTypeAdjustments: {
      STOCK: { betaMultiplier: 1.05, confidenceDelta: 0.03, rationale: "Single-name equities in India can reprice faster than index beta when rates jump." },
      ETF: { betaMultiplier: 1.01, confidenceDelta: 0.04, rationale: "ETF exposure usually tracks the benchmark path more tightly in rate shocks." },
      CRYPTO: { betaMultiplier: 1.10, confidenceDelta: -0.07, rationale: "Crypto remains a secondary liquidity-risk expression when real rates rise." },
      COMMODITY: { betaMultiplier: 0.95, confidenceDelta: -0.01, rationale: "Commodities can partly offset duration pain through inflation linkage." },
      MUTUAL_FUND: { betaMultiplier: 0.95, confidenceDelta: -0.05, rationale: "Mutual fund mandate inference adds uncertainty to duration mapping." },
    },
    factors: {
      equity: -0.12,
      rates: -0.11,
      gold: 0.07,
      usd: -0.09,
      oil: 0.08,
      credit: -0.08,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.12,
        maxDrawdown: -0.16,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.01 },
          { day: 14, drawdown: -0.03 },
          { day: 21, drawdown: -0.06 },
          { day: 28, drawdown: -0.08 },
          { day: 35, drawdown: -0.11 },
          { day: 42, drawdown: -0.14 },
          { day: 49, drawdown: -0.16 },
          { day: 56, drawdown: -0.15 },
          { day: 63, drawdown: -0.13 },
          { day: 70, drawdown: -0.12 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.09,
        maxDrawdown: -0.14,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.01 },
          { day: 14, drawdown: -0.02 },
          { day: 21, drawdown: -0.04 },
          { day: 28, drawdown: -0.06 },
          { day: 35, drawdown: -0.09 },
          { day: 42, drawdown: -0.12 },
          { day: 49, drawdown: -0.14 },
          { day: 56, drawdown: -0.12 },
          { day: 63, drawdown: -0.10 },
          { day: 70, drawdown: -0.09 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.07,
        maxDrawdown: -0.02,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: 0.01 },
          { day: 14, drawdown: 0.03 },
          { day: 21, drawdown: 0.05 },
          { day: 28, drawdown: 0.07 },
          { day: 35, drawdown: 0.04 },
          { day: 42, drawdown: 0.01 },
          { day: 49, drawdown: -0.02 },
          { day: 56, drawdown: 0.00 },
          { day: 63, drawdown: 0.04 },
          { day: 70, drawdown: 0.07 },
        ],
      },
    ],
  },
  {
    id: "tech-bubble-crash",
    name: "Tech Bubble Crash (India)",
    region: "IN",
    period: { start: "2021-10-01", end: "2022-10-31" },
    description: "Expensive platform and IT leadership unwind, funding appetite shrinks and speculative digital-growth exposures suffer larger drawdowns than the broad index.",
    color: "cyan",
    severity: "Extreme",
    shockType: "tech-bubble",
    narrative: {
      headline: "When growth leadership breaks in India, expensive tech and platform names usually get hit harder than broad domestic beta.",
      howItTransmits: "Tech unwind pressure moves through valuation compression, weaker funding appetite and slower growth expectations for digital leaders.",
      dominantDrivers: ["Valuation reset", "Funding scarcity", "Growth leadership unwind"],
      pressurePoints: ["Expensive IT", "Platform stories", "Speculative digital growth"],
      resilienceThemes: ["Banks", "Defensive consumption", "Gold in INR"],
    },
    assetTypeAdjustments: {
      STOCK: { betaMultiplier: 1.10, confidenceDelta: 0.03, rationale: "Single-name tech and platform equities tend to underperform broad beta in growth unwinds." },
      ETF: { betaMultiplier: 1.03, confidenceDelta: 0.04, rationale: "ETF exposure diversifies some single-name tech collapse risk." },
      CRYPTO: { betaMultiplier: 1.15, confidenceDelta: -0.08, rationale: "Crypto usually trades like speculative liquidity beta during tech-led de-risking." },
      COMMODITY: { betaMultiplier: 0.90, confidenceDelta: 0.00, rationale: "Commodity-linked assets can offer relative ballast when tech leadership unwinds." },
      MUTUAL_FUND: { betaMultiplier: 0.97, confidenceDelta: -0.05, rationale: "Mutual fund style inference reduces precision on concentrated growth mandates." },
    },
    factors: {
      equity: -0.18,
      rates: 0.01,
      gold: 0.10,
      usd: -0.03,
      oil: 0.02,
      credit: -0.09,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.18,
        maxDrawdown: -0.23,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.02 },
          { day: 20, drawdown: -0.05 },
          { day: 30, drawdown: -0.08 },
          { day: 40, drawdown: -0.11 },
          { day: 50, drawdown: -0.15 },
          { day: 60, drawdown: -0.19 },
          { day: 70, drawdown: -0.23 },
          { day: 80, drawdown: -0.21 },
          { day: 90, drawdown: -0.19 },
          { day: 100, drawdown: -0.18 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.11,
        maxDrawdown: -0.16,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.01 },
          { day: 20, drawdown: -0.03 },
          { day: 30, drawdown: -0.05 },
          { day: 40, drawdown: -0.07 },
          { day: 50, drawdown: -0.10 },
          { day: 60, drawdown: -0.13 },
          { day: 70, drawdown: -0.16 },
          { day: 80, drawdown: -0.14 },
          { day: 90, drawdown: -0.12 },
          { day: 100, drawdown: -0.11 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.10,
        maxDrawdown: -0.03,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: 0.01 },
          { day: 20, drawdown: 0.03 },
          { day: 30, drawdown: 0.05 },
          { day: 40, drawdown: 0.07 },
          { day: 50, drawdown: 0.04 },
          { day: 60, drawdown: 0.00 },
          { day: 70, drawdown: -0.03 },
          { day: 80, drawdown: 0.01 },
          { day: 90, drawdown: 0.06 },
          { day: 100, drawdown: 0.10 },
        ],
      },
    ],
  },
  {
    id: "oil-spike",
    name: "Oil Spike (India)",
    region: "IN",
    period: { start: "2022-02-01", end: "2022-06-30" },
    description: "Crude shock hurts import-sensitive India through inflation, margin pressure and rupee vulnerability while hard-asset hedges gain relative support.",
    color: "orange",
    severity: "Moderate",
    shockType: "oil-spike",
    narrative: {
      headline: "Higher crude usually hits India through imported inflation, weaker margins, and a tougher macro backdrop for consumer demand.",
      howItTransmits: "Oil spikes in India transmit through higher import costs, inflation repricing, and a tougher backdrop for rate-sensitive sectors.",
      dominantDrivers: ["Imported inflation", "Margin squeeze", "Macro defensiveness"],
      pressurePoints: ["Transport", "Consumer discretionary", "Rate-sensitive cyclicals"],
      resilienceThemes: ["Gold in INR", "Defensives", "Some commodity-linked exposures"],
    },
    assetTypeAdjustments: {
      STOCK: { betaMultiplier: 1.04, confidenceDelta: 0.03, rationale: "Import-cost-sensitive Indian equities often underperform benchmark beta in oil spikes." },
      ETF: { betaMultiplier: 1.00, confidenceDelta: 0.04, rationale: "ETF exposure broadly reflects inflation and sector rotation without as much idiosyncratic cost pressure." },
      CRYPTO: { betaMultiplier: 1.05, confidenceDelta: -0.06, rationale: "Crypto linkage is looser and mostly comes through broader risk and liquidity conditions." },
      COMMODITY: { betaMultiplier: 1.10, confidenceDelta: 0.01, rationale: "Commodity-linked assets can benefit when inflation is led by energy." },
      MUTUAL_FUND: { betaMultiplier: 0.97, confidenceDelta: -0.05, rationale: "Mutual fund oil sensitivity depends on mandate, so inference reduces confidence." },
    },
    factors: {
      equity: -0.10,
      rates: -0.06,
      gold: 0.08,
      usd: -0.05,
      oil: 0.32,
      credit: -0.06,
    },
    proxyPaths: [
      {
        proxy: "NIFTYBEES.NS",
        label: "NIFTY 50 (NIFTYBEES)",
        totalReturn: -0.10,
        maxDrawdown: -0.14,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.01 },
          { day: 14, drawdown: -0.03 },
          { day: 21, drawdown: -0.05 },
          { day: 28, drawdown: -0.08 },
          { day: 35, drawdown: -0.11 },
          { day: 42, drawdown: -0.14 },
          { day: 49, drawdown: -0.13 },
          { day: 56, drawdown: -0.12 },
          { day: 63, drawdown: -0.11 },
          { day: 70, drawdown: -0.10 },
        ],
      },
      {
        proxy: "BANKBEES.NS",
        label: "NIFTY Bank (BANKBEES)",
        totalReturn: -0.09,
        maxDrawdown: -0.13,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.01 },
          { day: 14, drawdown: -0.02 },
          { day: 21, drawdown: -0.04 },
          { day: 28, drawdown: -0.06 },
          { day: 35, drawdown: -0.09 },
          { day: 42, drawdown: -0.12 },
          { day: 49, drawdown: -0.13 },
          { day: 56, drawdown: -0.12 },
          { day: 63, drawdown: -0.10 },
          { day: 70, drawdown: -0.09 },
        ],
      },
      {
        proxy: "GOLDBEES.NS",
        label: "Gold INR (GOLDBEES)",
        totalReturn: 0.08,
        maxDrawdown: -0.02,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: 0.01 },
          { day: 14, drawdown: 0.03 },
          { day: 21, drawdown: 0.05 },
          { day: 28, drawdown: 0.07 },
          { day: 35, drawdown: 0.04 },
          { day: 42, drawdown: 0.00 },
          { day: 49, drawdown: -0.02 },
          { day: 56, drawdown: 0.01 },
          { day: 63, drawdown: 0.05 },
          { day: 70, drawdown: 0.08 },
        ],
      },
    ],
  },
];
