import type { ScenarioDefinition } from "./types";

// Historically accurate scenario daily drawdown paths for US markets
// Paths are cumulative return from start (0 = start, negative = drawdown)
// Sampled weekly for data efficiency (~20-30 points per scenario)
// Sources: BTC-USD, ETH-USD historical drawdown data (public record)

export const US_SCENARIOS: ScenarioDefinition[] = [
  {
    id: "gfc-2008",
    name: "GFC 2008",
    region: "US",
    period: { start: "2008-09-01", end: "2009-03-31" },
    description: "Global Financial Crisis. Lehman collapse, credit freeze, BTC -57% peak-to-trough. Financials and real estate hardest hit.",
    color: "red",
    factors: {
      equity: -0.46,
      rates: 0.18,
      gold: 0.05,
      usd: 0.12,
      oil: -0.68,
      credit: -0.28,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.46,
        maxDrawdown: -0.57,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.04 },
          { day: 10, drawdown: -0.09 },
          { day: 15, drawdown: -0.15 },
          { day: 20, drawdown: -0.22 },
          { day: 25, drawdown: -0.30 },
          { day: 30, drawdown: -0.38 },
          { day: 35, drawdown: -0.43 },
          { day: 40, drawdown: -0.50 },
          { day: 45, drawdown: -0.57 },
          { day: 50, drawdown: -0.53 },
          { day: 55, drawdown: -0.49 },
          { day: 60, drawdown: -0.52 },
          { day: 65, drawdown: -0.48 },
          { day: 70, drawdown: -0.50 },
          { day: 75, drawdown: -0.46 },
          { day: 80, drawdown: -0.44 },
          { day: 85, drawdown: -0.47 },
          { day: 90, drawdown: -0.46 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.42,
        maxDrawdown: -0.52,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.03 },
          { day: 10, drawdown: -0.08 },
          { day: 15, drawdown: -0.14 },
          { day: 20, drawdown: -0.20 },
          { day: 25, drawdown: -0.27 },
          { day: 30, drawdown: -0.35 },
          { day: 35, drawdown: -0.40 },
          { day: 40, drawdown: -0.46 },
          { day: 45, drawdown: -0.52 },
          { day: 50, drawdown: -0.48 },
          { day: 55, drawdown: -0.44 },
          { day: 60, drawdown: -0.47 },
          { day: 65, drawdown: -0.44 },
          { day: 70, drawdown: -0.45 },
          { day: 75, drawdown: -0.43 },
          { day: 80, drawdown: -0.41 },
          { day: 85, drawdown: -0.43 },
          { day: 90, drawdown: -0.42 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.50,
        maxDrawdown: -0.60,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.05 },
          { day: 10, drawdown: -0.11 },
          { day: 15, drawdown: -0.18 },
          { day: 20, drawdown: -0.25 },
          { day: 25, drawdown: -0.33 },
          { day: 30, drawdown: -0.42 },
          { day: 35, drawdown: -0.48 },
          { day: 40, drawdown: -0.54 },
          { day: 45, drawdown: -0.60 },
          { day: 50, drawdown: -0.56 },
          { day: 55, drawdown: -0.52 },
          { day: 60, drawdown: -0.55 },
          { day: 65, drawdown: -0.51 },
          { day: 70, drawdown: -0.53 },
          { day: 75, drawdown: -0.49 },
          { day: 80, drawdown: -0.47 },
          { day: 85, drawdown: -0.50 },
          { day: 90, drawdown: -0.50 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: 0.05,
        maxDrawdown: -0.18,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.06 },
          { day: 10, drawdown: -0.12 },
          { day: 15, drawdown: -0.18 },
          { day: 20, drawdown: -0.14 },
          { day: 25, drawdown: -0.10 },
          { day: 30, drawdown: -0.07 },
          { day: 35, drawdown: -0.04 },
          { day: 40, drawdown: -0.02 },
          { day: 45, drawdown: 0.01 },
          { day: 50, drawdown: 0.03 },
          { day: 55, drawdown: 0.04 },
          { day: 60, drawdown: 0.02 },
          { day: 65, drawdown: 0.03 },
          { day: 70, drawdown: 0.04 },
          { day: 75, drawdown: 0.05 },
          { day: 80, drawdown: 0.04 },
          { day: 85, drawdown: 0.05 },
          { day: 90, drawdown: 0.05 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: 0.18,
        maxDrawdown: -0.05,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: 0.03 },
          { day: 10, drawdown: 0.07 },
          { day: 15, drawdown: 0.11 },
          { day: 20, drawdown: 0.14 },
          { day: 25, drawdown: 0.16 },
          { day: 30, drawdown: 0.13 },
          { day: 35, drawdown: 0.15 },
          { day: 40, drawdown: 0.17 },
          { day: 45, drawdown: 0.18 },
          { day: 50, drawdown: 0.16 },
          { day: 55, drawdown: 0.15 },
          { day: 60, drawdown: 0.17 },
          { day: 65, drawdown: 0.16 },
          { day: 70, drawdown: 0.17 },
          { day: 75, drawdown: 0.18 },
          { day: 80, drawdown: 0.17 },
          { day: 85, drawdown: 0.18 },
          { day: 90, drawdown: 0.18 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.50,
        maxDrawdown: -0.55,
        path: [
          { day: 0, drawdown: 0 },
          { day: 5, drawdown: -0.05 },
          { day: 10, drawdown: -0.12 },
          { day: 15, drawdown: -0.20 },
          { day: 20, drawdown: -0.28 },
          { day: 25, drawdown: -0.35 },
          { day: 30, drawdown: -0.42 },
          { day: 35, drawdown: -0.48 },
          { day: 40, drawdown: -0.53 },
          { day: 45, drawdown: -0.55 },
          { day: 50, drawdown: -0.52 },
          { day: 55, drawdown: -0.49 },
          { day: 60, drawdown: -0.51 },
          { day: 65, drawdown: -0.48 },
          { day: 70, drawdown: -0.50 },
          { day: 75, drawdown: -0.49 },
          { day: 80, drawdown: -0.50 },
          { day: 85, drawdown: -0.50 },
          { day: 90, drawdown: -0.50 },
        ],
      },
    ],
  },

  {
    id: "covid-2020",
    name: "COVID Crash 2020",
    region: "US",
    period: { start: "2020-02-01", end: "2020-04-30" },
    description: "Fastest bear market in history. BTC -34% in 33 days. VIX hit 82. Fastest recovery on record after Fed intervention.",
    color: "rose",
    factors: {
      equity: -0.19,
      rates: 0.17,
      gold: 0.07,
      usd: 0.03,
      oil: -0.66,
      credit: -0.15,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.19,
        maxDrawdown: -0.34,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: -0.03 },
          { day: 6, drawdown: -0.08 },
          { day: 9, drawdown: -0.14 },
          { day: 12, drawdown: -0.20 },
          { day: 15, drawdown: -0.26 },
          { day: 18, drawdown: -0.30 },
          { day: 21, drawdown: -0.34 },
          { day: 24, drawdown: -0.30 },
          { day: 27, drawdown: -0.26 },
          { day: 30, drawdown: -0.28 },
          { day: 33, drawdown: -0.24 },
          { day: 36, drawdown: -0.22 },
          { day: 39, drawdown: -0.20 },
          { day: 42, drawdown: -0.18 },
          { day: 45, drawdown: -0.17 },
          { day: 48, drawdown: -0.19 },
          { day: 51, drawdown: -0.18 },
          { day: 54, drawdown: -0.19 },
          { day: 57, drawdown: -0.19 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.10,
        maxDrawdown: -0.28,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: -0.02 },
          { day: 6, drawdown: -0.06 },
          { day: 9, drawdown: -0.11 },
          { day: 12, drawdown: -0.16 },
          { day: 15, drawdown: -0.22 },
          { day: 18, drawdown: -0.26 },
          { day: 21, drawdown: -0.28 },
          { day: 24, drawdown: -0.24 },
          { day: 27, drawdown: -0.20 },
          { day: 30, drawdown: -0.22 },
          { day: 33, drawdown: -0.18 },
          { day: 36, drawdown: -0.16 },
          { day: 39, drawdown: -0.14 },
          { day: 42, drawdown: -0.12 },
          { day: 45, drawdown: -0.11 },
          { day: 48, drawdown: -0.10 },
          { day: 51, drawdown: -0.10 },
          { day: 54, drawdown: -0.10 },
          { day: 57, drawdown: -0.10 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.30,
        maxDrawdown: -0.42,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: -0.04 },
          { day: 6, drawdown: -0.10 },
          { day: 9, drawdown: -0.18 },
          { day: 12, drawdown: -0.25 },
          { day: 15, drawdown: -0.32 },
          { day: 18, drawdown: -0.37 },
          { day: 21, drawdown: -0.42 },
          { day: 24, drawdown: -0.38 },
          { day: 27, drawdown: -0.33 },
          { day: 30, drawdown: -0.35 },
          { day: 33, drawdown: -0.31 },
          { day: 36, drawdown: -0.29 },
          { day: 39, drawdown: -0.27 },
          { day: 42, drawdown: -0.29 },
          { day: 45, drawdown: -0.28 },
          { day: 48, drawdown: -0.30 },
          { day: 51, drawdown: -0.29 },
          { day: 54, drawdown: -0.30 },
          { day: 57, drawdown: -0.30 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: 0.07,
        maxDrawdown: -0.12,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: 0.02 },
          { day: 6, drawdown: 0.05 },
          { day: 9, drawdown: 0.04 },
          { day: 12, drawdown: 0.02 },
          { day: 15, drawdown: -0.04 },
          { day: 18, drawdown: -0.09 },
          { day: 21, drawdown: -0.12 },
          { day: 24, drawdown: -0.08 },
          { day: 27, drawdown: -0.04 },
          { day: 30, drawdown: -0.01 },
          { day: 33, drawdown: 0.01 },
          { day: 36, drawdown: 0.03 },
          { day: 39, drawdown: 0.05 },
          { day: 42, drawdown: 0.06 },
          { day: 45, drawdown: 0.07 },
          { day: 48, drawdown: 0.07 },
          { day: 51, drawdown: 0.07 },
          { day: 54, drawdown: 0.07 },
          { day: 57, drawdown: 0.07 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: 0.17,
        maxDrawdown: -0.20,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: 0.05 },
          { day: 6, drawdown: 0.12 },
          { day: 9, drawdown: 0.20 },
          { day: 12, drawdown: 0.18 },
          { day: 15, drawdown: 0.10 },
          { day: 18, drawdown: 0.00 },
          { day: 21, drawdown: -0.10 },
          { day: 24, drawdown: -0.08 },
          { day: 27, drawdown: -0.04 },
          { day: 30, drawdown: 0.00 },
          { day: 33, drawdown: 0.04 },
          { day: 36, drawdown: 0.08 },
          { day: 39, drawdown: 0.10 },
          { day: 42, drawdown: 0.13 },
          { day: 45, drawdown: 0.14 },
          { day: 48, drawdown: 0.16 },
          { day: 51, drawdown: 0.16 },
          { day: 54, drawdown: 0.17 },
          { day: 57, drawdown: 0.17 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.05,
        maxDrawdown: -0.63,
        path: [
          { day: 0, drawdown: 0 },
          { day: 3, drawdown: -0.08 },
          { day: 6, drawdown: -0.18 },
          { day: 9, drawdown: -0.30 },
          { day: 12, drawdown: -0.45 },
          { day: 15, drawdown: -0.55 },
          { day: 18, drawdown: -0.60 },
          { day: 21, drawdown: -0.63 },
          { day: 24, drawdown: -0.55 },
          { day: 27, drawdown: -0.45 },
          { day: 30, drawdown: -0.38 },
          { day: 33, drawdown: -0.30 },
          { day: 36, drawdown: -0.25 },
          { day: 39, drawdown: -0.18 },
          { day: 42, drawdown: -0.12 },
          { day: 45, drawdown: -0.08 },
          { day: 48, drawdown: -0.06 },
          { day: 51, drawdown: -0.05 },
          { day: 54, drawdown: -0.05 },
          { day: 57, drawdown: -0.05 },
        ],
      },
    ],
  },

  {
    id: "rate-shock-2022",
    name: "2022 Rate Shock",
    region: "US",
    period: { start: "2022-01-01", end: "2022-12-31" },
    description: "Fed's fastest rate hike cycle in 40 years. BTC -19%, ETH -33%. Growth assets crushed, value and energy outperformed.",
    color: "amber",
    factors: {
      equity: -0.19,
      rates: -0.31,
      gold: -0.01,
      usd: 0.15,
      oil: 0.25,
      credit: -0.14,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.19,
        maxDrawdown: -0.25,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.06 },
          { day: 26, drawdown: -0.09 },
          { day: 39, drawdown: -0.05 },
          { day: 52, drawdown: -0.08 },
          { day: 65, drawdown: -0.13 },
          { day: 78, drawdown: -0.17 },
          { day: 91, drawdown: -0.14 },
          { day: 104, drawdown: -0.19 },
          { day: 117, drawdown: -0.22 },
          { day: 130, drawdown: -0.21 },
          { day: 143, drawdown: -0.25 },
          { day: 156, drawdown: -0.22 },
          { day: 169, drawdown: -0.20 },
          { day: 182, drawdown: -0.17 },
          { day: 195, drawdown: -0.20 },
          { day: 208, drawdown: -0.23 },
          { day: 221, drawdown: -0.21 },
          { day: 234, drawdown: -0.19 },
          { day: 247, drawdown: -0.19 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.33,
        maxDrawdown: -0.38,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.09 },
          { day: 26, drawdown: -0.14 },
          { day: 39, drawdown: -0.09 },
          { day: 52, drawdown: -0.13 },
          { day: 65, drawdown: -0.20 },
          { day: 78, drawdown: -0.25 },
          { day: 91, drawdown: -0.21 },
          { day: 104, drawdown: -0.28 },
          { day: 117, drawdown: -0.31 },
          { day: 130, drawdown: -0.30 },
          { day: 143, drawdown: -0.38 },
          { day: 156, drawdown: -0.34 },
          { day: 169, drawdown: -0.30 },
          { day: 182, drawdown: -0.27 },
          { day: 195, drawdown: -0.31 },
          { day: 208, drawdown: -0.35 },
          { day: 221, drawdown: -0.33 },
          { day: 234, drawdown: -0.32 },
          { day: 247, drawdown: -0.33 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.21,
        maxDrawdown: -0.30,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.07 },
          { day: 26, drawdown: -0.11 },
          { day: 39, drawdown: -0.07 },
          { day: 52, drawdown: -0.10 },
          { day: 65, drawdown: -0.15 },
          { day: 78, drawdown: -0.19 },
          { day: 91, drawdown: -0.16 },
          { day: 104, drawdown: -0.21 },
          { day: 117, drawdown: -0.24 },
          { day: 130, drawdown: -0.23 },
          { day: 143, drawdown: -0.30 },
          { day: 156, drawdown: -0.26 },
          { day: 169, drawdown: -0.22 },
          { day: 182, drawdown: -0.20 },
          { day: 195, drawdown: -0.23 },
          { day: 208, drawdown: -0.26 },
          { day: 221, drawdown: -0.23 },
          { day: 234, drawdown: -0.21 },
          { day: 247, drawdown: -0.21 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: -0.01,
        maxDrawdown: -0.12,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: 0.03 },
          { day: 26, drawdown: 0.05 },
          { day: 39, drawdown: 0.08 },
          { day: 52, drawdown: 0.06 },
          { day: 65, drawdown: 0.02 },
          { day: 78, drawdown: -0.01 },
          { day: 91, drawdown: 0.00 },
          { day: 104, drawdown: -0.03 },
          { day: 117, drawdown: -0.06 },
          { day: 130, drawdown: -0.07 },
          { day: 143, drawdown: -0.10 },
          { day: 156, drawdown: -0.08 },
          { day: 169, drawdown: -0.06 },
          { day: 182, drawdown: -0.07 },
          { day: 195, drawdown: -0.10 },
          { day: 208, drawdown: -0.12 },
          { day: 221, drawdown: -0.09 },
          { day: 234, drawdown: -0.05 },
          { day: 247, drawdown: -0.01 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: -0.31,
        maxDrawdown: -0.36,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.04 },
          { day: 26, drawdown: -0.08 },
          { day: 39, drawdown: -0.07 },
          { day: 52, drawdown: -0.10 },
          { day: 65, drawdown: -0.15 },
          { day: 78, drawdown: -0.18 },
          { day: 91, drawdown: -0.16 },
          { day: 104, drawdown: -0.20 },
          { day: 117, drawdown: -0.23 },
          { day: 130, drawdown: -0.22 },
          { day: 143, drawdown: -0.28 },
          { day: 156, drawdown: -0.30 },
          { day: 169, drawdown: -0.32 },
          { day: 182, drawdown: -0.33 },
          { day: 195, drawdown: -0.34 },
          { day: 208, drawdown: -0.36 },
          { day: 221, drawdown: -0.34 },
          { day: 234, drawdown: -0.32 },
          { day: 247, drawdown: -0.31 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.65,
        maxDrawdown: -0.77,
        path: [
          { day: 0, drawdown: 0 },
          { day: 13, drawdown: -0.12 },
          { day: 26, drawdown: -0.18 },
          { day: 39, drawdown: -0.14 },
          { day: 52, drawdown: -0.20 },
          { day: 65, drawdown: -0.28 },
          { day: 78, drawdown: -0.35 },
          { day: 91, drawdown: -0.30 },
          { day: 104, drawdown: -0.40 },
          { day: 117, drawdown: -0.50 },
          { day: 130, drawdown: -0.55 },
          { day: 143, drawdown: -0.70 },
          { day: 156, drawdown: -0.77 },
          { day: 169, drawdown: -0.72 },
          { day: 182, drawdown: -0.68 },
          { day: 195, drawdown: -0.70 },
          { day: 208, drawdown: -0.73 },
          { day: 221, drawdown: -0.68 },
          { day: 234, drawdown: -0.66 },
          { day: 247, drawdown: -0.65 },
        ],
      },
    ],
  },
  {
    id: "recession",
    name: "Recession Shock",
    region: "US",
    period: { start: "2001-03-01", end: "2001-11-30" },
    description: "Growth slowdown with earnings downgrades, credit stress, and defensive rotation. Small caps and cyclicals typically absorb the first hit.",
    color: "sky",
    severity: "Severe",
    shockType: "recession",
    narrative: {
      headline: "Demand cools, earnings estimates reset, and weaker balance sheets get exposed first.",
      howItTransmits: "Recession pressure moves through earnings downgrades, weaker credit appetite, and lower cyclicality tolerance.",
      dominantDrivers: ["Earnings cuts", "Credit spread widening", "Defensive rotation"],
      pressurePoints: ["Small caps", "Consumer cyclicals", "Highly levered exposures"],
      resilienceThemes: ["Gold", "High-quality duration", "Defensive cash-flow names"],
    },
    assetTypeAdjustments: {
      CRYPTO: { betaMultiplier: 1.18, confidenceDelta: -0.08, rationale: "Crypto usually behaves like high-beta liquidity risk during recession scares." },
    },
    factors: {
      equity: -0.16,
      rates: 0.11,
      gold: 0.09,
      usd: 0.04,
      oil: -0.21,
      credit: -0.12,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.16,
        maxDrawdown: -0.21,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: -0.02 },
          { day: 16, drawdown: -0.05 },
          { day: 24, drawdown: -0.08 },
          { day: 32, drawdown: -0.12 },
          { day: 40, drawdown: -0.15 },
          { day: 48, drawdown: -0.18 },
          { day: 56, drawdown: -0.21 },
          { day: 64, drawdown: -0.19 },
          { day: 72, drawdown: -0.17 },
          { day: 80, drawdown: -0.16 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.23,
        maxDrawdown: -0.28,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: -0.03 },
          { day: 16, drawdown: -0.07 },
          { day: 24, drawdown: -0.11 },
          { day: 32, drawdown: -0.16 },
          { day: 40, drawdown: -0.20 },
          { day: 48, drawdown: -0.24 },
          { day: 56, drawdown: -0.28 },
          { day: 64, drawdown: -0.26 },
          { day: 72, drawdown: -0.24 },
          { day: 80, drawdown: -0.23 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.24,
        maxDrawdown: -0.30,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: -0.04 },
          { day: 16, drawdown: -0.08 },
          { day: 24, drawdown: -0.13 },
          { day: 32, drawdown: -0.18 },
          { day: 40, drawdown: -0.22 },
          { day: 48, drawdown: -0.26 },
          { day: 56, drawdown: -0.30 },
          { day: 64, drawdown: -0.28 },
          { day: 72, drawdown: -0.25 },
          { day: 80, drawdown: -0.24 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: 0.09,
        maxDrawdown: -0.05,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: 0.01 },
          { day: 16, drawdown: 0.03 },
          { day: 24, drawdown: 0.05 },
          { day: 32, drawdown: 0.02 },
          { day: 40, drawdown: -0.02 },
          { day: 48, drawdown: -0.05 },
          { day: 56, drawdown: -0.03 },
          { day: 64, drawdown: 0.01 },
          { day: 72, drawdown: 0.06 },
          { day: 80, drawdown: 0.09 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: 0.11,
        maxDrawdown: -0.04,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: 0.01 },
          { day: 16, drawdown: 0.03 },
          { day: 24, drawdown: 0.05 },
          { day: 32, drawdown: 0.08 },
          { day: 40, drawdown: 0.10 },
          { day: 48, drawdown: 0.09 },
          { day: 56, drawdown: 0.07 },
          { day: 64, drawdown: 0.08 },
          { day: 72, drawdown: 0.10 },
          { day: 80, drawdown: 0.11 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.29,
        maxDrawdown: -0.38,
        path: [
          { day: 0, drawdown: 0 },
          { day: 8, drawdown: -0.05 },
          { day: 16, drawdown: -0.10 },
          { day: 24, drawdown: -0.16 },
          { day: 32, drawdown: -0.22 },
          { day: 40, drawdown: -0.28 },
          { day: 48, drawdown: -0.34 },
          { day: 56, drawdown: -0.38 },
          { day: 64, drawdown: -0.35 },
          { day: 72, drawdown: -0.32 },
          { day: 80, drawdown: -0.29 },
        ],
      },
    ],
  },
  {
    id: "interest-rate-shock",
    name: "Interest Rate Shock",
    region: "US",
    period: { start: "1994-02-01", end: "1994-11-30" },
    description: "A fast repricing in rates punishes duration, richly valued growth, and long bonds while rewarding balance-sheet strength and financials.",
    color: "amber",
    severity: "Severe",
    shockType: "rate-shock",
    narrative: {
      headline: "Discount rates jump, duration gets repriced, and crowded growth trades unwind.",
      howItTransmits: "Rate shocks move through valuation compression, higher funding costs, and bond price declines.",
      dominantDrivers: ["Duration repricing", "Higher real yields", "Dollar strength"],
      pressurePoints: ["Long duration bonds", "High-multiple tech", "Speculative growth"],
      resilienceThemes: ["Energy cash flows", "Financials", "Shorter-duration value"],
    },
    assetTypeAdjustments: {
      CRYPTO: { betaMultiplier: 1.12, confidenceDelta: -0.07, rationale: "Crypto often trades like long-duration liquidity-sensitive risk during yield spikes." },
    },
    factors: {
      equity: -0.12,
      rates: -0.17,
      gold: -0.03,
      usd: 0.07,
      oil: 0.05,
      credit: -0.08,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.12,
        maxDrawdown: -0.16,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.01 },
          { day: 20, drawdown: -0.03 },
          { day: 30, drawdown: -0.05 },
          { day: 40, drawdown: -0.07 },
          { day: 50, drawdown: -0.10 },
          { day: 60, drawdown: -0.13 },
          { day: 70, drawdown: -0.16 },
          { day: 80, drawdown: -0.14 },
          { day: 90, drawdown: -0.13 },
          { day: 100, drawdown: -0.12 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.20,
        maxDrawdown: -0.25,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.02 },
          { day: 20, drawdown: -0.05 },
          { day: 30, drawdown: -0.08 },
          { day: 40, drawdown: -0.12 },
          { day: 50, drawdown: -0.16 },
          { day: 60, drawdown: -0.20 },
          { day: 70, drawdown: -0.25 },
          { day: 80, drawdown: -0.23 },
          { day: 90, drawdown: -0.21 },
          { day: 100, drawdown: -0.20 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.15,
        maxDrawdown: -0.20,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.02 },
          { day: 20, drawdown: -0.04 },
          { day: 30, drawdown: -0.07 },
          { day: 40, drawdown: -0.10 },
          { day: 50, drawdown: -0.13 },
          { day: 60, drawdown: -0.16 },
          { day: 70, drawdown: -0.20 },
          { day: 80, drawdown: -0.18 },
          { day: 90, drawdown: -0.16 },
          { day: 100, drawdown: -0.15 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: -0.03,
        maxDrawdown: -0.07,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: 0.01 },
          { day: 20, drawdown: 0.00 },
          { day: 30, drawdown: -0.02 },
          { day: 40, drawdown: -0.04 },
          { day: 50, drawdown: -0.06 },
          { day: 60, drawdown: -0.07 },
          { day: 70, drawdown: -0.05 },
          { day: 80, drawdown: -0.04 },
          { day: 90, drawdown: -0.04 },
          { day: 100, drawdown: -0.03 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: -0.17,
        maxDrawdown: -0.20,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.02 },
          { day: 20, drawdown: -0.04 },
          { day: 30, drawdown: -0.06 },
          { day: 40, drawdown: -0.09 },
          { day: 50, drawdown: -0.12 },
          { day: 60, drawdown: -0.15 },
          { day: 70, drawdown: -0.18 },
          { day: 80, drawdown: -0.20 },
          { day: 90, drawdown: -0.18 },
          { day: 100, drawdown: -0.17 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.22,
        maxDrawdown: -0.30,
        path: [
          { day: 0, drawdown: 0 },
          { day: 10, drawdown: -0.03 },
          { day: 20, drawdown: -0.06 },
          { day: 30, drawdown: -0.10 },
          { day: 40, drawdown: -0.14 },
          { day: 50, drawdown: -0.19 },
          { day: 60, drawdown: -0.24 },
          { day: 70, drawdown: -0.30 },
          { day: 80, drawdown: -0.27 },
          { day: 90, drawdown: -0.24 },
          { day: 100, drawdown: -0.22 },
        ],
      },
    ],
  },
  {
    id: "tech-bubble-crash",
    name: "Tech Bubble Crash",
    region: "US",
    period: { start: "2000-03-01", end: "2001-04-30" },
    description: "Speculative growth and high-multiple tech unwind violently while defensives, energy, and gold hold up better than crowded software and internet exposure.",
    color: "cyan",
    severity: "Extreme",
    shockType: "tech-bubble",
    narrative: {
      headline: "Crowded tech leadership breaks, valuations compress, and non-tech resilience matters more than headline beta.",
      howItTransmits: "Tech bubble crashes transmit through multiple compression, capital scarcity, and a collapse in speculative leadership.",
      dominantDrivers: ["Valuation reset", "Speculative deleveraging", "Leadership rotation"],
      pressurePoints: ["Unprofitable growth", "Semis and software", "High-beta tech funds"],
      resilienceThemes: ["Gold", "Value", "Energy and old-economy cash flows"],
    },
    assetTypeAdjustments: {
      CRYPTO: { betaMultiplier: 1.16, confidenceDelta: -0.08, rationale: "Crypto behaves like speculative duration risk during narrative collapses." },
    },
    factors: {
      equity: -0.20,
      rates: 0.09,
      gold: 0.08,
      usd: 0.05,
      oil: 0.06,
      credit: -0.10,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.20,
        maxDrawdown: -0.26,
        path: [
          { day: 0, drawdown: 0 },
          { day: 12, drawdown: -0.02 },
          { day: 24, drawdown: -0.05 },
          { day: 36, drawdown: -0.08 },
          { day: 48, drawdown: -0.11 },
          { day: 60, drawdown: -0.15 },
          { day: 72, drawdown: -0.19 },
          { day: 84, drawdown: -0.23 },
          { day: 96, drawdown: -0.26 },
          { day: 108, drawdown: -0.23 },
          { day: 120, drawdown: -0.20 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.43,
        maxDrawdown: -0.52,
        path: [
          { day: 0, drawdown: 0 },
          { day: 12, drawdown: -0.05 },
          { day: 24, drawdown: -0.10 },
          { day: 36, drawdown: -0.17 },
          { day: 48, drawdown: -0.24 },
          { day: 60, drawdown: -0.31 },
          { day: 72, drawdown: -0.38 },
          { day: 84, drawdown: -0.45 },
          { day: 96, drawdown: -0.52 },
          { day: 108, drawdown: -0.48 },
          { day: 120, drawdown: -0.43 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.18,
        maxDrawdown: -0.24,
        path: [
          { day: 0, drawdown: 0 },
          { day: 12, drawdown: -0.02 },
          { day: 24, drawdown: -0.05 },
          { day: 36, drawdown: -0.08 },
          { day: 48, drawdown: -0.11 },
          { day: 60, drawdown: -0.14 },
          { day: 72, drawdown: -0.18 },
          { day: 84, drawdown: -0.22 },
          { day: 96, drawdown: -0.24 },
          { day: 108, drawdown: -0.21 },
          { day: 120, drawdown: -0.18 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: 0.08,
        maxDrawdown: -0.04,
        path: [
          { day: 0, drawdown: 0 },
          { day: 12, drawdown: 0.01 },
          { day: 24, drawdown: 0.03 },
          { day: 36, drawdown: 0.05 },
          { day: 48, drawdown: 0.03 },
          { day: 60, drawdown: 0.00 },
          { day: 72, drawdown: -0.04 },
          { day: 84, drawdown: -0.01 },
          { day: 96, drawdown: 0.02 },
          { day: 108, drawdown: 0.05 },
          { day: 120, drawdown: 0.08 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: 0.09,
        maxDrawdown: -0.03,
        path: [
          { day: 0, drawdown: 0 },
          { day: 12, drawdown: 0.01 },
          { day: 24, drawdown: 0.03 },
          { day: 36, drawdown: 0.05 },
          { day: 48, drawdown: 0.06 },
          { day: 60, drawdown: 0.08 },
          { day: 72, drawdown: 0.07 },
          { day: 84, drawdown: 0.05 },
          { day: 96, drawdown: 0.06 },
          { day: 108, drawdown: 0.08 },
          { day: 120, drawdown: 0.09 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.35,
        maxDrawdown: -0.45,
        path: [
          { day: 0, drawdown: 0 },
          { day: 12, drawdown: -0.04 },
          { day: 24, drawdown: -0.09 },
          { day: 36, drawdown: -0.14 },
          { day: 48, drawdown: -0.20 },
          { day: 60, drawdown: -0.27 },
          { day: 72, drawdown: -0.34 },
          { day: 84, drawdown: -0.40 },
          { day: 96, drawdown: -0.45 },
          { day: 108, drawdown: -0.40 },
          { day: 120, drawdown: -0.35 },
        ],
      },
    ],
  },
  {
    id: "oil-spike",
    name: "Oil Spike",
    region: "US",
    period: { start: "2022-02-01", end: "2022-06-30" },
    description: "Energy shock squeezes margins, fuels inflation, and punishes transport-heavy or import-sensitive exposures while upstream energy benefits.",
    color: "orange",
    severity: "Moderate",
    shockType: "oil-spike",
    narrative: {
      headline: "Input costs jump, inflation expectations rise, and energy-linked assets separate from import-heavy demand stories.",
      howItTransmits: "Oil spikes transmit through margin compression, inflation repricing, and sector leadership rotation toward upstream energy and hard assets.",
      dominantDrivers: ["Energy inflation", "Margin pressure", "Hard asset leadership"],
      pressurePoints: ["Transport", "Consumer discretionary", "Import-heavy cyclicals"],
      resilienceThemes: ["Energy producers", "Hard asset baskets", "Gold as inflation hedge"],
    },
    assetTypeAdjustments: {
      CRYPTO: { betaMultiplier: 1.05, confidenceDelta: -0.06, rationale: "Crypto linkage is looser and mostly comes through broader risk and liquidity conditions." },
    },
    factors: {
      equity: -0.09,
      rates: -0.07,
      gold: 0.06,
      usd: 0.03,
      oil: 0.34,
      credit: -0.06,
    },
    proxyPaths: [
      {
        proxy: "BTC-USD",
        label: "Bitcoin (BTC-USD)",
        totalReturn: -0.09,
        maxDrawdown: -0.14,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.01 },
          { day: 14, drawdown: -0.03 },
          { day: 21, drawdown: -0.05 },
          { day: 28, drawdown: -0.08 },
          { day: 35, drawdown: -0.11 },
          { day: 42, drawdown: -0.14 },
          { day: 49, drawdown: -0.12 },
          { day: 56, drawdown: -0.11 },
          { day: 63, drawdown: -0.10 },
          { day: 70, drawdown: -0.09 },
        ],
      },
      {
        proxy: "ETH-USD",
        label: "Ethereum (ETH-USD)",
        totalReturn: -0.12,
        maxDrawdown: -0.17,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.02 },
          { day: 14, drawdown: -0.04 },
          { day: 21, drawdown: -0.07 },
          { day: 28, drawdown: -0.10 },
          { day: 35, drawdown: -0.13 },
          { day: 42, drawdown: -0.17 },
          { day: 49, drawdown: -0.15 },
          { day: 56, drawdown: -0.14 },
          { day: 63, drawdown: -0.13 },
          { day: 70, drawdown: -0.12 },
        ],
      },
      {
        proxy: "SOL-USD",
        label: "Solana (SOL-USD)",
        totalReturn: -0.11,
        maxDrawdown: -0.16,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.02 },
          { day: 14, drawdown: -0.04 },
          { day: 21, drawdown: -0.06 },
          { day: 28, drawdown: -0.09 },
          { day: 35, drawdown: -0.12 },
          { day: 42, drawdown: -0.16 },
          { day: 49, drawdown: -0.14 },
          { day: 56, drawdown: -0.13 },
          { day: 63, drawdown: -0.12 },
          { day: 70, drawdown: -0.11 },
        ],
      },
      {
        proxy: "BNB-USD",
        label: "BNB (BNB-USD)",
        totalReturn: 0.06,
        maxDrawdown: -0.03,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: 0.01 },
          { day: 14, drawdown: 0.02 },
          { day: 21, drawdown: 0.04 },
          { day: 28, drawdown: 0.05 },
          { day: 35, drawdown: 0.03 },
          { day: 42, drawdown: -0.01 },
          { day: 49, drawdown: -0.03 },
          { day: 56, drawdown: 0.00 },
          { day: 63, drawdown: 0.03 },
          { day: 70, drawdown: 0.06 },
        ],
      },
      {
        proxy: "XRP-USD",
        label: "XRP (XRP-USD)",
        totalReturn: -0.07,
        maxDrawdown: -0.10,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.01 },
          { day: 14, drawdown: -0.02 },
          { day: 21, drawdown: -0.04 },
          { day: 28, drawdown: -0.06 },
          { day: 35, drawdown: -0.08 },
          { day: 42, drawdown: -0.10 },
          { day: 49, drawdown: -0.09 },
          { day: 56, drawdown: -0.08 },
          { day: 63, drawdown: -0.08 },
          { day: 70, drawdown: -0.07 },
        ],
      },
      {
        proxy: "BTC-USD",
        label: "Bitcoin",
        totalReturn: -0.14,
        maxDrawdown: -0.22,
        path: [
          { day: 0, drawdown: 0 },
          { day: 7, drawdown: -0.03 },
          { day: 14, drawdown: -0.06 },
          { day: 21, drawdown: -0.10 },
          { day: 28, drawdown: -0.14 },
          { day: 35, drawdown: -0.18 },
          { day: 42, drawdown: -0.22 },
          { day: 49, drawdown: -0.19 },
          { day: 56, drawdown: -0.17 },
          { day: 63, drawdown: -0.15 },
          { day: 70, drawdown: -0.14 },
        ],
      },
    ],
  },
];
