"use client";

import React, { useState } from "react";
import { Check, FileText } from "lucide-react";
import { cn } from "@/lib/utils";

interface Message {
  role: "user" | "assistant";
  content: string;
}

interface ExportButtonProps {
  messages: Message[];
  symbol?: string;
  assetName?: string;
  className?: string;
}

function buildMarkdownReport(messages: Message[], symbol?: string, assetName?: string): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });

  const title = assetName ? `Lyra Analysis: ${assetName}${symbol ? ` (${symbol})` : ""}` : "Lyra AI Analysis Report";

  const lines: string[] = [
    `# ${title}`,
    ``,
    `**Generated:** ${date}  `,
    `**Platform:** InsightAlpha AI — Elite Plan`,
    ``,
    `---`,
    ``,
  ];

  messages.forEach((msg, i) => {
    if (msg.role === "user") {
      lines.push(`## Query ${Math.ceil((i + 1) / 2)}`);
      lines.push(``);
      lines.push(`> ${msg.content}`);
      lines.push(``);
    } else {
      // Strip source tags and tool result blocks for clean export
      const cleaned = msg.content
        .replace(/\[SOURCES\][\s\S]*?\[\/SOURCES\]/g, "")
        .replace(/\[TOOL_RESULTS\][\s\S]*?\[\/TOOL_RESULTS\]/g, "")
        .replace(/\[RELATED_QUESTIONS\][\s\S]*?\[\/RELATED_QUESTIONS\]/g, "")
        .trim();

      lines.push(`### Lyra Response`);
      lines.push(``);
      lines.push(cleaned);
      lines.push(``);
      lines.push(`---`);
      lines.push(``);
    }
  });

  lines.push(`*This report was generated by Lyra AI on the InsightAlpha AI platform. For informational purposes only — not financial advice.*`);

  return lines.join("\n");
}

export function ExportButton({ messages, symbol, assetName, className }: ExportButtonProps) {
  const [copied, setCopied] = useState(false);

  const hasContent = messages.some((m) => m.role === "assistant" && m.content.trim());

  const handleExport = () => {
    const markdown = buildMarkdownReport(messages, symbol, assetName);

    // Download as .md file
    const blob = new Blob([markdown], { type: "text/markdown;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    try {
      const a = document.createElement("a");
      a.href = url;
      const filename = symbol
        ? `lyra-${symbol.toLowerCase().replace(/[^a-z0-9]/g, "-")}-${new Date().toISOString().split("T")[0]}.md`
        : `lyra-report-${new Date().toISOString().split("T")[0]}.md`;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
    } finally {
      URL.revokeObjectURL(url);
    }

    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (!hasContent) return null;

  return (
    <button
      onClick={handleExport}
      className={cn(
        "flex items-center gap-1.5 px-2.5 py-1.5 rounded-2xl border transition-all text-[9px] font-bold uppercase tracking-wider",
        copied
          ? "border-emerald-500/40 bg-emerald-500/10 text-emerald-400"
          : "border-white/5 bg-card/60 text-muted-foreground hover:border-primary/30 hover:text-primary hover:bg-primary/5",
        className,
      )}
      title="Save conversation as Markdown report"
    >
      {copied ? (
        <>
          <Check className="h-3 w-3" />
          Saved
        </>
      ) : (
        <>
          <FileText className="h-3 w-3" />
          Save Report
        </>
      )}
    </button>
  );
}
