/**
 * Learning Module Registry
 * Central registry of all learning modules with metadata.
 * Module content lives in markdown files; this registry provides
 * the metadata needed for listing, filtering, and badge evaluation.
 */

export interface ModuleMetadata {
  slug: string;
  title: string;
  category: string;
  xpReward: number;
  estimatedTime: string;
  prerequisite: string | null;
  badgeContribution: string | null;
  isEliteOnly: boolean;
  description: string;
  order: number; // display order within category
  /** If set, module is only shown to users in that region */
  regionOnly?: "IN" | "US";
}

// ─── Module Definitions ───
// Each entry maps to a markdown file in src/lib/learning/modules/{category}/{slug}.md

const MODULES: ModuleMetadata[] = [
  // ── Fundamentals ──
  {
    slug: "what-is-trend-score",
    title: "What is a Trend Score?",
    category: "fundamentals",
    xpReward: 15,
    estimatedTime: "45 seconds",
    prerequisite: null,
    badgeContribution: "trend-aware",
    isEliteOnly: false,
    description: "Learn how trend scores measure price direction consistency — not predictions.",
    order: 1,
  },
  {
    slug: "what-is-momentum",
    title: "What is Momentum?",
    category: "fundamentals",
    xpReward: 15,
    estimatedTime: "45 seconds",
    prerequisite: null,
    badgeContribution: "trend-aware",
    isEliteOnly: false,
    description: "Understand how momentum captures the rate of change in price trends.",
    order: 2,
  },
  {
    slug: "what-is-volatility",
    title: "What is Volatility?",
    category: "fundamentals",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "risk-conscious",
    isEliteOnly: false,
    description: "Why volatility is a measure of uncertainty, not just risk.",
    order: 3,
  },
  {
    slug: "what-is-liquidity",
    title: "What is Liquidity?",
    category: "fundamentals",
    xpReward: 15,
    estimatedTime: "45 seconds",
    prerequisite: null,
    badgeContribution: "risk-conscious",
    isEliteOnly: false,
    description: "How liquidity affects your ability to enter and exit positions.",
    order: 4,
  },
  {
    slug: "what-is-sentiment",
    title: "What is Sentiment?",
    category: "fundamentals",
    xpReward: 15,
    estimatedTime: "45 seconds",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How market sentiment is measured and why it matters for contrarian signals.",
    order: 5,
  },
  {
    slug: "what-is-trust-score",
    title: "What is a Trust Score?",
    category: "fundamentals",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "risk-conscious",
    isEliteOnly: false,
    description: "How trust scores assess institutional quality, governance, and reliability.",
    order: 6,
  },

  // ── Crypto ──
  {
    slug: "understanding-network-activity",
    title: "Understanding Network Activity",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "crypto-risk-conscious",
    isEliteOnly: false,
    description: "What on-chain activity reveals about a crypto network's health.",
    order: 1,
  },
  {
    slug: "crypto-structural-risk",
    title: "Crypto Structural Risk",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "crypto-risk-conscious",
    isEliteOnly: false,
    description: "Dependency risk, governance risk, and why protocol architecture matters.",
    order: 2,
  },
  {
    slug: "holder-stability-explained",
    title: "Holder Stability Explained",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "crypto-risk-conscious",
    isEliteOnly: false,
    description: "How holder behavior patterns signal conviction vs speculation.",
    order: 3,
  },
  {
    slug: "crypto-trust-model",
    title: "The Crypto Trust Model",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "crypto-structural-risk",
    badgeContribution: "crypto-risk-conscious",
    isEliteOnly: false,
    description: "How 6 components combine to assess crypto trustworthiness.",
    order: 4,
  },

  // ── Portfolio Analysis ──
  {
    slug: "portfolio-lookthrough-basics",
    title: "Portfolio Lookthrough Basics",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "portfolio-transparency",
    isEliteOnly: false,
    description: "Why you need to look through your portfolio to understand what you actually own.",
    order: 1,
  },
  {
    slug: "concentration-risk",
    title: "Concentration Risk",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "portfolio-lookthrough-basics",
    badgeContribution: "portfolio-transparency",
    isEliteOnly: false,
    description: "How top-heavy holdings create hidden risk in 'diversified' portfolios.",
    order: 2,
  },
  {
    slug: "factor-exposure",
    title: "Factor Exposure",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "portfolio-lookthrough-basics",
    badgeContribution: "portfolio-transparency",
    isEliteOnly: false,
    description: "Value, growth, momentum, quality, size — what factor tilts mean for your portfolio.",
    order: 3,
  },
  {
    slug: "correlation-risk",
    title: "Correlation Risk",
    category: "crypto",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "portfolio-lookthrough-basics",
    badgeContribution: "portfolio-transparency",
    isEliteOnly: false,
    description: "Why holding multiple correlated assets might give you less diversification than you think.",
    order: 4,
  },

  // ── Macro Strategy ──
  {
    slug: "regime-sensitivity",
    title: "Regime Sensitivity",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How crypto assets behave differently in risk-on vs risk-off environments.",
    order: 1,
  },
  {
    slug: "crypto-seasonality",
    title: "Crypto Seasonality",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "Historical seasonal patterns in crypto — and why they're not predictions.",
    order: 2,
  },
  {
    slug: "cross-asset-correlations",
    title: "Cross-Asset Correlations",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How crypto assets relate to each other and to broader markets.",
    order: 3,
  },
  {
    slug: "market-cycles",
    title: "Market Cycles",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "Understanding crypto market cycles and where we might be in the current one.",
    order: 4,
  },

  // ── Regime ──
  {
    slug: "what-is-market-regime",
    title: "What is a Market Regime?",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "regime-reader",
    isEliteOnly: false,
    description: "How the MRDE classifies market environments and why it matters.",
    order: 1,
  },
  {
    slug: "regime-and-your-portfolio",
    title: "Regime & Your Portfolio",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "regime-reader",
    isEliteOnly: false,
    description: "How different assets perform across market regimes.",
    order: 2,
  },
  {
    slug: "defensive-vs-risk-on",
    title: "Defensive vs Risk-On",
    category: "regime",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "what-is-market-regime",
    badgeContribution: "regime-reader",
    isEliteOnly: false,
    description: "Understanding the spectrum from risk-on to risk-off and what drives transitions.",
    order: 3,
  },

  // ── Discovery ──
  {
    slug: "reading-discovery-cards",
    title: "Reading Discovery Cards",
    category: "discovery",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How to interpret DRS scores, archetypes, and context on discovery cards.",
    order: 1,
  },
  {
    slug: "score-inflections",
    title: "Score Inflections",
    category: "discovery",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "reading-discovery-cards",
    badgeContribution: "momentum-scholar",
    isEliteOnly: false,
    description: "What it means when a score shifts significantly — and what it doesn't.",
    order: 2,
  },
  {
    slug: "peer-divergence",
    title: "Peer Divergence",
    category: "discovery",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "reading-discovery-cards",
    badgeContribution: null,
    isEliteOnly: false,
    description: "When an asset breaks from its peer group — signal or noise?",
    order: 3,
  },

  // ── Platform Workflows ──
  {
    slug: "ask-lyra-workflow",
    title: "Ask Lyra Workflow",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "lyra-user",
    isEliteOnly: false,
    description: "How to turn Lyra from a chat box into a real analysis workflow.",
    order: 1,
  },
  {
    slug: "how-lyra-tiers-work",
    title: "How Lyra Tiers Work",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "ask-lyra-workflow",
    badgeContribution: "lyra-user",
    isEliteOnly: false,
    description: "SIMPLE vs MODERATE vs COMPLEX — how Lyra routes your question and what changes at each level.",
    order: 2,
  },
  {
    slug: "lyra-query-types",
    title: "Lyra Query Types",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "ask-lyra-workflow",
    badgeContribution: "lyra-user",
    isEliteOnly: false,
    description: "Single-asset analysis, Compare, Shock Simulator — when to use each and how Lyra adapts.",
    order: 3,
  },
  {
    slug: "credits-and-plans-explained",
    title: "Credits & Plans Explained",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How credits are spent per query complexity, how monthly resets work, and what each plan unlocks.",
    order: 4,
  },
  {
    slug: "lyra-memory-explained",
    title: "Lyra Memory Explained",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "ask-lyra-workflow",
    badgeContribution: "lyra-user",
    isEliteOnly: false,
    description: "How Lyra distills key facts from your conversations to give you better context-aware analysis over time.",
    order: 5,
  },
  {
    slug: "browse-assets-workflow",
    title: "Browse Assets Workflow",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How to move from the asset browser into a high-conviction asset page review.",
    order: 6,
  },
  {
    slug: "watchlist-workflow",
    title: "Watchlist Workflow",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How to use Watchlist as a monitoring queue instead of a dumping ground.",
    order: 7,
  },
  {
    slug: "rewards-and-xp-explained",
    title: "Rewards & XP Explained",
    category: "platform",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: null,
    isEliteOnly: false,
    description: "How XP, streaks, badges, and learning path rewards compound across the product.",
    order: 8,
  },

  // ── Advanced (Elite Only) ──
  {
    slug: "cross-asset-correlation",
    title: "Cross-Asset Correlation",
    category: "advanced",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "cross-asset-thinker",
    isEliteOnly: true,
    description: "How correlations between asset classes shift during regime transitions.",
    order: 1,
  },
  {
    slug: "regime-transition-patterns",
    title: "Regime Transition Patterns",
    category: "advanced",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "cross-asset-thinker",
    isEliteOnly: true,
    description: "Historical patterns in how markets transition between regimes.",
    order: 2,
  },
  {
    slug: "historical-analogs",
    title: "Historical Analogs",
    category: "advanced",
    xpReward: 20,
    estimatedTime: "2.5 minutes",
    prerequisite: "regime-transition-patterns",
    badgeContribution: "cross-asset-thinker",
    isEliteOnly: true,
    description: "Using past market episodes to contextualize current conditions.",
    order: 3,
  },
  {
    slug: "macro-analysis",
    title: "Macro Analysis",
    category: "advanced",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "regime-sensitivity",
    badgeContribution: null,
    isEliteOnly: true,
    description: "Advanced macro analysis through the lens of crypto regimes and USD dynamics.",
    order: 4,
  },
  {
    slug: "portfolio-advanced-analysis",
    title: "Advanced Portfolio Analysis",
    category: "advanced",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "portfolio-lookthrough-basics",
    badgeContribution: null,
    isEliteOnly: true,
    description: "Deep lookthrough analysis, concentration detection, and cross-position overlap.",
    order: 5,
  },

  // ── Signals ──
  {
    slug: "what-is-signal-strength",
    title: "What is Signal Strength?",
    category: "signals",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "signal-reader",
    isEliteOnly: false,
    description: "How the composite signal strength score is built from 4 layers — and what each label means.",
    order: 1,
  },
  {
    slug: "reading-confidence-levels",
    title: "Reading Confidence Levels",
    category: "signals",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: "what-is-signal-strength",
    badgeContribution: "signal-reader",
    isEliteOnly: false,
    description: "Why a High Confidence Bullish signal is very different from a Low Confidence Bullish one.",
    order: 2,
  },
  {
    slug: "score-dynamics-explained",
    title: "Score Dynamics & Momentum",
    category: "signals",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-signal-strength",
    badgeContribution: "signal-reader",
    isEliteOnly: false,
    description: "What momentum, acceleration, and percentile rank of a score tell you about trajectory.",
    order: 3,
  },
  {
    slug: "factor-alignment-explained",
    title: "Factor Alignment & Regime Fit",
    category: "signals",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "signal-reader",
    isEliteOnly: false,
    description: "How the ARCS compatibility score measures whether an asset is suited to the current regime.",
    order: 4,
  },

  // ── Portfolio ──
  {
    slug: "portfolio-health-explained",
    title: "Portfolio Health Score",
    category: "portfolio",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "portfolio-builder",
    isEliteOnly: false,
    description: "How the portfolio health meter and fragility index assess your overall exposure.",
    order: 1,
  },
  {
    slug: "monte-carlo-explained",
    title: "Monte Carlo Simulation",
    category: "portfolio",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "portfolio-health-explained",
    badgeContribution: "portfolio-builder",
    isEliteOnly: false,
    description: "What the probabilistic fan chart means — and why it is not a price prediction.",
    order: 2,
  },
  {
    slug: "arcs-explained",
    title: "ARCS — Regime Compatibility Score",
    category: "portfolio",
    xpReward: 20,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "portfolio-builder",
    isEliteOnly: false,
    description: "How the Asset-Regime Compatibility Score tells you whether each holding is suited to the current macro environment.",
    order: 3,
  },
  {
    slug: "stress-testing-basics",
    title: "Portfolio Stress Testing",
    category: "portfolio",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "monte-carlo-explained",
    badgeContribution: "stress-tester",
    isEliteOnly: true,
    description: "Running your portfolio through historical crash scenarios to understand tail risk.",
    order: 4,
  },
  {
    slug: "compare-assets-guide",
    title: "Comparative Asset Analysis",
    category: "portfolio",
    xpReward: 20,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-signal-strength",
    badgeContribution: "stress-tester",
    isEliteOnly: true,
    description: "How to use the Compare tool to evaluate assets side-by-side across scores, regime fit, and performance.",
    order: 5,
  },
  {
    slug: "shock-simulator-guide",
    title: "Shock Simulator",
    category: "portfolio",
    xpReward: 20,
    estimatedTime: "2 minutes",
    prerequisite: "portfolio-health-explained",
    badgeContribution: "stress-tester",
    isEliteOnly: true,
    description: "How the Shock Simulator replays historical crash scenarios against your portfolio — and what Lyra's interpretation adds.",
    order: 6,
  },

  // ── Intelligence ──
  {
    slug: "reading-analyst-signals",
    title: "Reading Analyst Signals",
    category: "intelligence",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "market-analyst",
    isEliteOnly: false,
    description: "Analyst consensus bars, price targets, and upgrade/downgrade events — what they reveal and what they don't.",
    order: 1,
  },
  {
    slug: "insider-transactions-explained",
    title: "Insider Transactions",
    category: "intelligence",
    xpReward: 15,
    estimatedTime: "1 minute",
    prerequisite: null,
    badgeContribution: "market-analyst",
    isEliteOnly: false,
    description: "Why insider buying and selling is a weak-but-real signal — and how MSPR measures it.",
    order: 2,
  },
  {
    slug: "sector-rotation-basics",
    title: "Sector Rotation Basics",
    category: "intelligence",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "market-analyst",
    isEliteOnly: false,
    description: "How sectors move through market regimes and what rotation signals look like in practice.",
    order: 3,
  },
  {
    slug: "market-narratives-explained",
    title: "Market Narratives Explained",
    category: "intelligence",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: "what-is-market-regime",
    badgeContribution: "market-analyst",
    isEliteOnly: false,
    description: "How to read the narratives page as a map of themes, pressure, and regime fit.",
    order: 4,
  },
  {
    slug: "market-events-explained",
    title: "Market Events Explained",
    category: "intelligence",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "market-analyst",
    isEliteOnly: false,
    description: "How the market events timeline helps you connect catalysts to score and regime shifts.",
    order: 5,
  },
  {
    slug: "crypto-market-structure",
    title: "Crypto Market Structure",
    category: "intelligence",
    xpReward: 15,
    estimatedTime: "1.5 minutes",
    prerequisite: null,
    badgeContribution: "global-investor",
    isEliteOnly: false,
    description: "Crypto market structure, BTC-USD dynamics, and how crypto regime behavior differs across global markets.",
    order: 6,
  },
];

// ─── Public API ───

/** Get all module metadata (sorted by category + order) */
export function getModuleRegistry(): ModuleMetadata[] {
  return [...MODULES].sort((a, b) => {
    if (a.category !== b.category) return a.category.localeCompare(b.category);
    return a.order - b.order;
  });
}

/** Get a single module's metadata by slug */
export function getModuleBySlug(slug: string): ModuleMetadata | undefined {
  return MODULES.find(m => m.slug === slug);
}

/** Get all module slugs in a category */
export function getModuleSlugsForCategory(category: string): string[] {
  return MODULES
    .filter(m => m.category === category)
    .sort((a, b) => a.order - b.order)
    .map(m => m.slug);
}

/** Get all categories */
export function getCategories(): string[] {
  return [...new Set(MODULES.map(m => m.category))];
}

/** Get total module count */
export function getTotalModuleCount(includeElite: boolean = true): number {
  return includeElite ? MODULES.length : MODULES.filter(m => !m.isEliteOnly).length;
}
